---
- hosts: tag_ProductID_Sample_v1_0_0
  remote_user: ec2-user
  become: yes
  tasks:
  - name: Download WAR to server
    copy:
     src: /ansible/playbooks/DEV01/appautomation/043643/sample-1.0.0.war
     dest: /opt/tomcat/webapps/sample-1.0.0.war
     owner: tomcat
     group: tomcat
     mode: 0644
     
  - name: Restart tomcat
    service: name=tomcat state=restarted